# Generated by Django 4.1.5 on 2023-03-26 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorPenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(default='unassigned', max_length=100)),
                ('item_name', models.CharField(default=None, max_length=100)),
                ('item_amount', models.IntegerField(default=1)),
                ('username', models.CharField(default=None, max_length=100)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('user_department', models.CharField(default=None, max_length=100)),
                ('user_duty', models.CharField(default=None, max_length=100)),
                ('director_fullname', models.CharField(default=None, max_length=200)),
                ('approval', models.CharField(default='unassigned', max_length=10)),
                ('description', models.TextField(default='unassigned', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, max_length=100)),
                ('item_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(default='unassigned', max_length=100)),
                ('item_name', models.CharField(default=None, max_length=100)),
                ('item_amount', models.IntegerField(default=1)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=100)),
                ('user_department', models.CharField(default=None, max_length=100)),
                ('user_duty', models.CharField(default=None, max_length=100)),
                ('approval', models.CharField(default='rejected', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('description', models.TextField(default='unassigned', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(default='unassigned', max_length=100)),
                ('item_name', models.CharField(default=None, max_length=100)),
                ('item_amount', models.IntegerField(default=1)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=100)),
                ('user_department', models.CharField(default=None, max_length=100)),
                ('user_duty', models.CharField(default=None, max_length=100)),
                ('officer_fullname', models.CharField(default='unassigned', max_length=200)),
                ('approval', models.CharField(default='unassigned', max_length=10)),
                ('description', models.TextField(default='unassigned', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='unassigned', max_length=100)),
                ('message', models.CharField(default='unassigned', max_length=200)),
                ('cus_id', models.CharField(default='unassigned', max_length=100)),
                ('additional_info', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='unassigned', max_length=100), default=list, size=None)),
            ],
        ),
    ]
