# Generated by Django 4.1.5 on 2023-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorpenrequest',
            old_name='description',
            new_name='user_description',
        ),
        migrations.RenameField(
            model_name='officerpenrequest',
            old_name='description',
            new_name='director_description',
        ),
        migrations.RenameField(
            model_name='processedrequest',
            old_name='description',
            new_name='director_description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='cus_id',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='officerpenrequest',
            name='user_description',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
        migrations.AddField(
            model_name='processedrequest',
            name='officer_description',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
        migrations.AddField(
            model_name='processedrequest',
            name='user_description',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
    ]
