# Generated by Django 4.1.5 on 2023-03-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_description_directorpenrequest_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerpenrequest',
            name='officer_fullname',
            field=models.CharField(default='unassigned', max_length=200),
        ),
        migrations.AlterField(
            model_name='directorpenrequest',
            name='director_fullname',
            field=models.CharField(default='`unassigned`', max_length=200),
        ),
    ]
